config/routes.rb
Rails.application.routes.draw do
  resources :rsvps
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :user
  validates :first_name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rsvps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  def new
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    if @rsvp.save
      redirect_to "/rsvps/#{@rsvp.id}"
    else
      render :new
    end
  end

  def show
    @rsvp = Rsvp.find_by(id: params[:id])
  end

  def edit
    @rsvp = Rsvp.find_by(id: params[:id])
  end

  def update
    @rsvp = Rsvp.find_by(id: params[:id])
    if @rsvp.update(rsvp_params)
      redirect_to "/rsvps/#{@rsvp.id}"
    else
      render :edit
    end
  end

  def destroy
    Rsvp.find_by(id: params[:id]).destroy
    redirect_to "/rsvps"
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:first_name, :last_name, :attending, :vegetarian, :guests  )
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeddingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rsvps/_form.html.erb
<%= form_for @rsvp do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :attending %>
    <%= f.check_box :attending %>
  </div>
  <div>
    <%= f.label :vegetarian %>
    <%= f.check_box :vegetarian %>
  </div>
  <div>
    <%= f.label :guests %>
    <%= f.text_field :guests %>
  </div>
  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/rsvps/edit.html.erb
<h1>Edit Invitation</h1>
<%= render "form" %>

app/views/rsvps/new.html.erb
<h1> Are you coming to my wedding!??!?!?!?</h1>


<%= render "form" %>

app/views/rsvps/show.html.erb
<h1>Reservation</h1>


<ul>
  <li>First Name: <%= @rsvp.first_name %></li>
  <li>Last Name: <%= @rsvp.last_name %></li>
</ul>

<%= link_to "Edit Reservation", edit_rsvp_path %>